#!/bin/sh

storepath="$1"

{ # Intersect two sets:

	# 1. all referrers of a store path
	nix-store --query --referrers-closure "${storepath}"

	# 2. all store paths directly required by the user profile
	nix-env --query --installed --out-path | sed "s,.*\\(/nix/store/.*$\\),\\1,"
} | sort | uniq --repeated
